# Generated by Django 5.2.9 on 2026-05-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signup_source',
            field=models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile App'), ('referral', 'Referral'), ('social', 'Social Media')], default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
