# Generated by Django 5.2.9 on 2026-03-05 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_country', models.CharField(choices=[('USA', 'United States'), ('UK', 'United Kingdom'), ('DE', 'Germany'), ('CA', 'Canada'), ('AU', 'Australia')], max_length=5)),
                ('target_degree_type', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Phd', 'PhD'), ('Diploma', 'Diploma')], max_length=20)),
                ('target_field', models.CharField(blank=True, help_text='Optional field of study e.g. Computer Science', max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('incomplete_profile', 'Incomplete Profile'), ('no_matches', 'No Matches Found')], default='completed', max_length=30)),
                ('overall_score', models.FloatField(default=0, help_text='Overall probability score 0-100')),
                ('total_programs_evaluated', models.PositiveIntegerField(default=0)),
                ('total_matches_found', models.PositiveIntegerField(default=0, help_text='Programs where student scored >= 50%')),
                ('score_breakdown', models.JSONField(default=dict, help_text='Per-factor score breakdown e.g. {gpa: 90, language: 75, financial: 60}')),
                ('profile_snapshot', models.JSONField(default=dict, help_text='Snapshot of student profile data used in this assessment')),
                ('missing_factors', models.JSONField(default=list, help_text="List of things the student is missing e.g. ['No language test', 'Insufficient funds']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UniversityMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability_score', models.FloatField()),
                ('gpa_score', models.FloatField(default=0)),
                ('language_score', models.FloatField(default=0)),
                ('financial_score', models.FloatField(default=0)),
                ('backlog_score', models.FloatField(default=0)),
                ('visa_history_score', models.FloatField(default=0)),
                ('acceptance_rate_score', models.FloatField(default=0)),
                ('eligibility', models.CharField(choices=[('likely', 'Likely'), ('possible', 'Possible'), ('reach', 'Reach'), ('unlikely', 'Unlikely')], max_length=20)),
                ('match_reasons', models.JSONField(default=list, help_text="e.g. ['GPA meets requirement', 'IELTS score qualifies']")),
                ('gap_reasons', models.JSONField(default=list, help_text="e.g. ['IELTS 0.5 below requirement', 'Savings may be insufficient']")),
                ('rank', models.PositiveIntegerField(default=1)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_matches', to='universities.universityprogram')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='assessments.visaassessment')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
