# Generated by Django 5.2.9 on 2026-03-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitymatch',
            name='cost_data',
            field=models.JSONField(default=dict, help_text='Complete cost estimate: tuition + living + visa + insurance + affordability'),
        ),
        migrations.AlterField(
            model_name='universitymatch',
            name='gap_reasons',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='universitymatch',
            name='match_reasons',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='visaassessment',
            name='missing_factors',
            field=models.JSONField(default=list, help_text='Profile gaps that affected scoring'),
        ),
        migrations.AlterField(
            model_name='visaassessment',
            name='overall_score',
            field=models.FloatField(default=0, help_text='Probability score 0-100'),
        ),
        migrations.AlterField(
            model_name='visaassessment',
            name='profile_snapshot',
            field=models.JSONField(default=dict, help_text='Student profile data at time of assessment'),
        ),
        migrations.AlterField(
            model_name='visaassessment',
            name='score_breakdown',
            field=models.JSONField(default=dict, help_text='Per-factor average scores across all evaluated programs'),
        ),
    ]
