# Generated by Django 5.2.9 on 2025-12-15 00:47

import django.core.validators
import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Unique key for frontend lookups', unique=True)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(choices=[('ALL', 'Universal'), ('USA', 'United States'), ('UK', 'United Kingdom'), ('DE', 'Germany')], default='ALL', max_length=10)),
                ('phase', models.CharField(choices=[('ADMISSION', 'University Admission'), ('VISA', 'Visa Application'), ('ENROLLMENT', 'Enrollment/Arrival')], default='ADMISSION', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('requires_original', models.BooleanField(default=False)),
                ('validity_months', models.PositiveIntegerField(blank=True, help_text='Expected validity period (e.g., 6 months for bank statements)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=documents.models.user_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), documents.models.validate_file_size])),
                ('status', models.CharField(choices=[('MISSING', 'Missing / Not Started'), ('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='MISSING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_instances', to='documents.documentdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='documents_u_user_id_2147d8_idx'), models.Index(fields=['user', 'expiry_date'], name='documents_u_user_id_d37068_idx')],
                'unique_together': {('user', 'document_definition')},
            },
        ),
    ]
