# Generated by Django 4.2.27 on 2026-02-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, help_text='AI confidence percentage (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='ai_extracted_data',
            field=models.JSONField(blank=True, help_text='Data extracted by Gemini LLM', null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='ai_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason if AI verification failed', null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='ai_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
