# Generated by Django 5.2.9 on 2026-05-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_userdocument_ai_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdefinition',
            name='requires_ai_extraction',
            field=models.BooleanField(default=True, help_text='If true, document will be sent to Gemini for metadata extraction and verification.'),
        ),
    ]
