# Generated by Django 5.2.9 on 2026-03-04 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='universitiesid from scraped data', max_length=20, unique=True)),
                ('uni_no', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('university_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Other', 'Other')], default='Public', max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(db_index=True, default='USA', max_length=10)),
                ('qs_world_ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('us_news_ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('offers_financial_aid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(db_index=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('degree_type', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Phd', 'PhD'), ('Diploma', 'Diploma')], db_index=True, max_length=20)),
                ('degree_name', models.CharField(blank=True, help_text='e.g. BS, MS, MBA', max_length=50)),
                ('is_stem', models.BooleanField(default=False)),
                ('ielts_required', models.FloatField(blank=True, help_text='Minimum IELTS overall band', null=True)),
                ('toefl_required', models.FloatField(blank=True, help_text='Minimum TOEFL iBT score', null=True)),
                ('pte_required', models.FloatField(blank=True, help_text='Minimum PTE score', null=True)),
                ('duolingo_required', models.FloatField(blank=True, help_text='Minimum Duolingo score', null=True)),
                ('min_gpa', models.FloatField(blank=True, help_text='Minimum GPA/percentage required', null=True)),
                ('max_backlogs', models.PositiveIntegerField(blank=True, help_text='Max allowed academic backlogs', null=True)),
                ('gre_required', models.CharField(blank=True, help_text='e.g. Waived, Required, Not Applicable', max_length=50)),
                ('gmat_required', models.CharField(blank=True, max_length=50)),
                ('tuition_fee_per_year', models.DecimalField(blank=True, decimal_places=2, help_text='International student annual tuition in USD', max_digits=10, null=True)),
                ('estimated_living_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated annual living cost in USD', max_digits=10, null=True)),
                ('application_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('app_fee_waiver_available', models.BooleanField(default=False)),
                ('acceptance_rate', models.FloatField(blank=True, help_text='Acceptance rate as percentage (0-100)', null=True)),
                ('duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('num_credits', models.PositiveIntegerField(blank=True, null=True)),
                ('semester', models.CharField(blank=True, choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Rolling', 'Rolling')], max_length=20)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('required_documents_raw', models.TextField(blank=True, help_text="Raw pipe-separated list from scraped data e.g. 'Passport |##| IELTS'")),
                ('application_link', models.URLField(blank=True)),
                ('department_link', models.URLField(blank=True)),
                ('total_scholarships', models.PositiveIntegerField(default=0)),
                ('total_scholarship_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university')),
            ],
            options={
                'ordering': ['university__name', 'program_name'],
            },
        ),
    ]
