# Generated by Django 5.2.9 on 2025-12-14 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], default='single', max_length=20)),
                ('nationality', models.CharField(help_text='Country of Citizenship', max_length=100)),
                ('residence_country', models.CharField(help_text='Country of Residence', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('profession_title', models.CharField(blank=True, max_length=100)),
                ('current_employer', models.CharField(blank=True, max_length=150, null=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('has_travel_history', models.BooleanField(default=False)),
                ('has_additional_residency', models.BooleanField(default=False)),
                ('has_additional_passport', models.BooleanField(default=False)),
                ('has_visa_refusal_history', models.BooleanField(default=False, help_text='Important for risk assessment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('high_school', 'High School / A-Levels'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD')], max_length=50)),
                ('degree_title', models.CharField(max_length=150)),
                ('institute_name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=True)),
                ('score', models.CharField(help_text='CGPA or Percentage', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='student_profile.studentprofile')),
            ],
        ),
    ]
