# Generated by Django 5.2.9 on 2025-12-14 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('ielts', 'IELTS'), ('toefl', 'TOEFL'), ('pte', 'PTE'), ('duolingo', 'Duolingo'), ('other', 'Other')], max_length=20)),
                ('overall_score', models.FloatField()),
                ('reading', models.FloatField()),
                ('listening', models.FloatField()),
                ('writing', models.FloatField()),
                ('speaking', models.FloatField()),
                ('test_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scores', to='student_profile.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('income_currency', models.CharField(default='USD', max_length=10)),
                ('income_source', models.CharField(blank=True, help_text='Job, Business, Freelance, etc.', max_length=100)),
                ('approx_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('savings_currency', models.CharField(default='USD', max_length=10)),
                ('has_sponsor', models.BooleanField(default=False)),
                ('sponsor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('sponsor_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to='student_profile.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTravelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('visa_type', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('refusal_or_overstay', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_history', to='student_profile.studentprofile')),
            ],
        ),
    ]
