# Generated by Django 5.2.9 on 2026-03-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0002_languagetest_studentfinancialprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='target_country',
            field=models.CharField(blank=True, help_text='Target Country for Study', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='target_degree_type',
            field=models.CharField(blank=True, help_text='Target Degree Type', max_length=100, null=True),
        ),
    ]
